### ISSUE TITLE
Refactor accounts_test to use ex_machina

### ISSUE THREAD

**Issue by zacck** [LittleKidogo/MoneyLog#56] opened 2018-03-06 05:39 UTC
## Expected Behavior
The accounts context test currently is a generated test that would be very brittle to use due to the duplication needed, however, we can remedy this  by converting the Accounts context test to use `ex_machina` and also adding coverage for the user changesets to separate those two

## Actual Behavior
At the moment the `accounts_test` is a generated test file that uses test fixtures. 

## Acceptance Criteria
- [ ] Refactor the test to use ex_machina 
- [ ] Tests drive the user changesets

## Specifications

  - Version: 0.0.1-rcauth

**Comment by zacck-zz** [comment] 2018-03-11 18:11
duplicate of #67

**Closed** 2018-03-12 06:29 UTC
Labels: duplicate, good first issue
